apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: __NAMESPACE__
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: __NAMESPACE__
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: monitoring-service-account
      containers:
      - name: prometheus
        image: __REGISTRY_URI__/prometheus:__TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: rules
          mountPath: /etc/prometheus/rules/alert_rules.yml
          subPath: alert_rules.yml
        - name: prometheus-data
          mountPath: /prometheus
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: config
        configMap:
          name: monitoring-configmap
          items:
            - key: prometheus.yml
              path: prometheus.yml
      - name: rules
        configMap:
          name: monitoring-configmap
          items:
            - key: alert_rules.yml
              path: alert_rules.yml
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2