repos:
-   repo: local
    hooks:
    -   id: pydantic-compatibility
        name: Pydantic Compatibility Check
        entry: python backend/check_pydantic_compatibility.py
        language: system
        files: ^backend/.*\.py$
        pass_filenames: false
