version: "1.0"
base_url: "{sentry_base_url}"
categories:
  projects:
    name: "Projects"
    base_path: "/api/0/organizations/{organization_slug}"
    endpoints:
      list:
        path: "/projects/"
        method: "GET"
        description: "List organization projects"
        cache_ttl: 3600
        
      detail:
        path: "/projects/{project_slug}/"
        method: "GET"
        description: "Get project details"
        cache_ttl: 3600
        
      stats:
        path: "/projects/{project_slug}/stats/"
        method: "GET"
        description: "Get project statistics"
        cache_ttl: 300
        
      users:
        path: "/projects/{project_slug}/users/"
        method: "GET"
        description: "Get project users"
        cache_ttl: 3600
        
  project_keys:
    name: "Project Keys"
    base_path: "/api/0/projects/{organization_slug}/{project_slug}"
    endpoints:
      list:
        path: "/keys/"
        method: "GET"
        description: "List project keys"
        cache_ttl: 3600
        
      detail:
        path: "/keys/{key_id}/"
        method: "GET"
        description: "Get key details"
        cache_ttl: 3600
