/**
 * AISummarySection Component Tests
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { MantineProvider } from '@mantine/core';
import { AISummarySection } from '../AISummarySection';
import { AIAnalysis } from '../../../types/enrichment';

const renderWithProviders = (component: React.ReactElement) => {
  return render(<MantineProvider>{component}</MantineProvider>);
};

describe('AISummarySection', () => {
  describe('Empty state', () => {
    it('should show message when no analysis available', () => {
      renderWithProviders(<AISummarySection />);

      expect(screen.getByText(/No AI analysis available yet/)).toBeTruthy();
    });
  });

  describe('With analysis data', () => {
    const mockAnalysis: AIAnalysis = {
      summary: 'This is a database connection timeout error. The application lost connection to the database.',
      confidence: 0.85,
      citations: [
        {
          text: 'Similar issue #123 had the same root cause',
          source: 'similar_issue_123',
        },
        {
          text: 'Release notes mention database migration',
          source: 'release_context',
        },
      ],
      generatedAt: new Date().toISOString(),
    };

    it('should display AI summary text', () => {
      renderWithProviders(<AISummarySection analysis={mockAnalysis} />);

      expect(screen.getByText(/database connection timeout/)).toBeTruthy();
    });

    it('should show confidence badge', () => {
      renderWithProviders(<AISummarySection analysis={mockAnalysis} />);

      expect(screen.getByText(/High Confidence/)).toBeTruthy();
      expect(screen.getByText(/85%/)).toBeTruthy();
    });

    it('should display "Generated by AI" badge', () => {
      renderWithProviders(<AISummarySection analysis={mockAnalysis} />);

      expect(screen.getByText(/Generated by AI/)).toBeTruthy();
    });

    it('should show warning for low confidence', () => {
      const lowConfidenceAnalysis: AIAnalysis = {
        ...mockAnalysis,
        confidence: 0.3,
      };

      renderWithProviders(<AISummarySection analysis={lowConfidenceAnalysis} />);

      expect(screen.getByText(/low confidence/i)).toBeTruthy();
    });
  });

  describe('Citations', () => {
    const mockAnalysis: AIAnalysis = {
      summary: 'Error caused by timeout [1]. See release notes [2].',
      confidence: 0.75,
      citations: [
        { text: 'Timeout issue', source: 'similar_issue_123' },
        { text: 'Release notes', source: 'release_context' },
      ],
      generatedAt: new Date().toISOString(),
    };

    it('should render clickable citations', () => {
      const onCitationClick = vi.fn();
      renderWithProviders(
        <AISummarySection analysis={mockAnalysis} onCitationClick={onCitationClick} />
      );

      const citation1 = screen.getByText('[1]');
      const citation2 = screen.getByText('[2]');

      expect(citation1).toBeTruthy();
      expect(citation2).toBeTruthy();

      fireEvent.click(citation1);
      expect(onCitationClick).toHaveBeenCalledWith('similar_issue_123');

      fireEvent.click(citation2);
      expect(onCitationClick).toHaveBeenCalledWith('release_context');
    });

    it('should list all citations in references section', () => {
      renderWithProviders(<AISummarySection analysis={mockAnalysis} />);

      expect(screen.getByText(/References:/)).toBeTruthy();
      expect(screen.getByText(/Timeout issue/)).toBeTruthy();
      expect(screen.getByText(/Release notes/)).toBeTruthy();
    });
  });

  describe('Why This Answer button', () => {
    it('should show button when callback provided', () => {
      const onWhyThisAnswer = vi.fn();
      const mockAnalysis: AIAnalysis = {
        summary: 'Test summary',
        confidence: 0.8,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(
        <AISummarySection analysis={mockAnalysis} onWhyThisAnswer={onWhyThisAnswer} />
      );

      const button = screen.getByText(/Why this answer/);
      expect(button).toBeTruthy();

      fireEvent.click(button);
      expect(onWhyThisAnswer).toHaveBeenCalled();
    });

    it('should not show button when callback not provided', () => {
      const mockAnalysis: AIAnalysis = {
        summary: 'Test summary',
        confidence: 0.8,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(<AISummarySection analysis={mockAnalysis} />);

      const button = screen.queryByText(/Why this answer/);
      expect(button).toBeNull();
    });
  });

  describe('Confidence levels', () => {
    it('should show green badge for high confidence (>= 0.8)', () => {
      const analysis: AIAnalysis = {
        summary: 'Test',
        confidence: 0.9,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(<AISummarySection analysis={analysis} />);
      expect(screen.getByText(/High Confidence/)).toBeTruthy();
    });

    it('should show blue badge for medium confidence (0.6-0.8)', () => {
      const analysis: AIAnalysis = {
        summary: 'Test',
        confidence: 0.7,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(<AISummarySection analysis={analysis} />);
      expect(screen.getByText(/Medium Confidence/)).toBeTruthy();
    });

    it('should show yellow badge for low confidence (0.4-0.6)', () => {
      const analysis: AIAnalysis = {
        summary: 'Test',
        confidence: 0.5,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(<AISummarySection analysis={analysis} />);
      expect(screen.getByText(/Low Confidence/)).toBeTruthy();
    });

    it('should show red badge for very low confidence (< 0.4)', () => {
      const analysis: AIAnalysis = {
        summary: 'Test',
        confidence: 0.2,
        generatedAt: new Date().toISOString(),
      };

      renderWithProviders(<AISummarySection analysis={analysis} />);
      expect(screen.getByText(/Very Low Confidence/)).toBeTruthy();
    });
  });
});
