/**
 * AISummarySection Component
 *
 * Displays AI-generated analysis with confidence scoring and citations
 */

import { Paper, Title, Text, Badge, Group, Stack, Button, Anchor } from '@mantine/core';
import { IconRobot, IconBulb, IconAlertTriangle } from '@tabler/icons-react';
import { AIAnalysis } from '../../types/enrichment';

interface AISummarySectionProps {
  analysis?: AIAnalysis;
  onCitationClick?: (source: string) => void;
  onWhyThisAnswer?: () => void;
}

/**
 * Get confidence badge color based on score
 */
const getConfidenceBadgeColor = (confidence: number): string => {
  if (confidence >= 0.8) return 'green';
  if (confidence >= 0.6) return 'blue';
  if (confidence >= 0.4) return 'yellow';
  return 'red';
};

/**
 * Get confidence label
 */
const getConfidenceLabel = (confidence: number): string => {
  if (confidence >= 0.8) return 'High Confidence';
  if (confidence >= 0.6) return 'Medium Confidence';
  if (confidence >= 0.4) return 'Low Confidence';
  return 'Very Low Confidence';
};

/**
 * Parse citation markers in text and make them clickable
 */
const parseCitations = (
  text: string,
  citations: AIAnalysis['citations'],
  onCitationClick?: (source: string) => void
): React.ReactNode => {
  if (!citations || citations.length === 0) {
    return text;
  }

  const parts: React.ReactNode[] = [];
  let lastIndex = 0;

  // Find citation markers like [1], [2], etc.
  const citationRegex = /\[(\d+)\]/g;
  let match: RegExpExecArray | null;

  while ((match = citationRegex.exec(text)) !== null) {
    const citationNumber = parseInt(match[1], 10);
    const citation = citations[citationNumber - 1];

    // Add text before citation
    if (match.index > lastIndex) {
      parts.push(text.substring(lastIndex, match.index));
    }

    // Add clickable citation
    if (citation && onCitationClick) {
      parts.push(
        <Anchor
          key={`citation-${match.index}`}
          component="button"
          onClick={() => onCitationClick(citation.source)}
          size="sm"
          style={{ verticalAlign: 'super', fontSize: '0.75em' }}
        >
          [{citationNumber}]
        </Anchor>
      );
    } else {
      parts.push(match[0]);
    }

    lastIndex = match.index + match[0].length;
  }

  // Add remaining text
  if (lastIndex < text.length) {
    parts.push(text.substring(lastIndex));
  }

  return <>{parts}</>;
};

export const AISummarySection: React.FC<AISummarySectionProps> = ({
  analysis,
  onCitationClick,
  onWhyThisAnswer,
}) => {
  if (!analysis) {
    return (
      <Paper p="md" withBorder style={{ backgroundColor: '#f8f9fa' }}>
        <Group gap="xs">
          <IconAlertTriangle size={20} color="gray" />
          <Text c="dimmed" size="sm">
            No AI analysis available yet. Try refreshing or wait for analysis to complete.
          </Text>
        </Group>
      </Paper>
    );
  }

  const confidenceColor = getConfidenceBadgeColor(analysis.confidence);
  const confidenceLabel = getConfidenceLabel(analysis.confidence);
  const showWarning = analysis.confidence < 0.6;

  return (
    <Paper p="md" withBorder style={{ backgroundColor: '#e7f5ff' }}>
      <Stack gap="md">
        {/* Header */}
        <Group justify="space-between" wrap="nowrap">
          <Group gap="xs">
            <IconRobot size={20} color="#228be6" />
            <Title order={5}>AI Summary</Title>
            <Badge size="xs" variant="light" color="blue">
              Generated by AI
            </Badge>
          </Group>

          <Group gap="xs">
            <Badge color={confidenceColor} variant="light" size="sm">
              {confidenceLabel} ({Math.round(analysis.confidence * 100)}%)
            </Badge>
          </Group>
        </Group>

        {/* Warning for low confidence */}
        {showWarning && (
          <Group gap="xs" p="xs" style={{ backgroundColor: '#fff3cd', borderRadius: 4 }}>
            <IconAlertTriangle size={16} color="#856404" />
            <Text size="sm" c="#856404">
              This analysis has low confidence. Please verify with source data before taking action.
            </Text>
          </Group>
        )}

        {/* Summary with citations */}
        <Text style={{ lineHeight: 1.6 }}>
          {parseCitations(analysis.summary, analysis.citations, onCitationClick)}
        </Text>

        {/* Citations list */}
        {analysis.citations && analysis.citations.length > 0 && (
          <Stack gap="xs">
            <Text size="sm" fw={500} c="dimmed">
              References:
            </Text>
            {analysis.citations.map((citation, index) => (
              <Group key={index} gap="xs" wrap="nowrap">
                <Text size="xs" c="dimmed" style={{ minWidth: 20 }}>
                  [{index + 1}]
                </Text>
                <Text size="xs" c="dimmed">
                  {citation.text}
                  {citation.source && (
                    <Text span size="xs" c="blue" ml={4}>
                      (Source: {citation.source})
                    </Text>
                  )}
                </Text>
              </Group>
            ))}
          </Stack>
        )}

        {/* Actions */}
        <Group gap="xs">
          {onWhyThisAnswer && (
            <Button
              variant="subtle"
              size="xs"
              leftSection={<IconBulb size={14} />}
              onClick={onWhyThisAnswer}
            >
              Why this answer?
            </Button>
          )}
          <Text size="xs" c="dimmed">
            Generated {new Date(analysis.generatedAt).toLocaleString()}
          </Text>
        </Group>
      </Stack>
    </Paper>
  );
};

export default AISummarySection;
